# Generated by Django 3.1.6 on 2021-02-06 21:09

from django.db import migrations, models

import url.generator


class Migration(migrations.Migration):
    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug_url',
            field=models.SlugField(default=url.generator.Generator.generate, null=True, unique=True),
        ),
    ]
