# Generated by Django 3.1.6 on 2021-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20210206_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
